(() => {
'use strict';
const D=JSON.parse(document.getElementById('replay-data').textContent), $=id=>document.getElementById(id);
const labels={observe:'观察 RGB',look:'转向观察',act:'执行动作',update_plan:'更新计划',remember:'记录记忆',recall:'读取记忆',list_skills:'查看技能目录',read_skill:'阅读技能',finish:'结束任务'};
const motors={navigate_to:'接近选定目标',grasp:'抓取',place_inside:'放入',place_on_top:'放到表面',open:'打开',close:'关闭',toggle_on:'开启',toggle_off:'关闭开关',release:'释放',wait:'等待'};
let edition=D.explained_video?.status==='passed'?'explained':'raw';
let fromVideo=false;let index=0,view='head',timer=null;
const text=(id,value)=>$(id).textContent=value??'—';
function node(tag,txt,cls){const n=document.createElement(tag);if(txt!==undefined)n.textContent=txt;if(cls)n.className=cls;return n}
function stat(target,label,value){const n=node('div',undefined,'stat');n.append(node('strong',String(value??'未记录')),node('small',label));$(target).append(n)}
function title(s){return s.tool==='act'?(motors[s.arguments.primitive||s.arguments.skill]||s.arguments.primitive||s.arguments.skill):labels[s.tool]||s.tool}
function visible(){return D.steps.filter(s=>$('filter').value==='all'||($('filter').value==='motor'&&s.is_motor_action)||($('filter').value==='observation'&&s.new_observation)||($('filter').value==='failed'&&s.status!=='passed'))}
function paintTimeline(){const root=$('timeline');root.replaceChildren();for(const s of visible()){const b=node('button',undefined,`timeline-step ${s.status} ${s.index===index+1?'active':''}`);b.dataset.step=s.index;b.setAttribute('aria-current',String(s.index===index+1));b.append(node('span',String(s.index).padStart(2,'0'),'step-number'));const wrap=node('span');wrap.append(node('b',title(s)),node('small',`${s.tool} · +${s.elapsed_seconds.toFixed(1)}s${s.status==='failed'?' · 失败':''}`));b.append(wrap);b.onclick=()=>{stop();select(s.index-1)};root.append(b)}if(!root.children.length)root.append(node('p','没有此类记录。','muted'))}
function frame(side,obs,s){const root=$(side+'-frame');root.replaceChildren();const image=obs?.images.find(i=>i.view===view);if(!image?.file){root.append(node('div',obs?'该视角没有已归档图像。':'此时尚未通过工具返回任何RGB。','empty'));text(side+'-meta',obs?`revision ${obs.revision}`:'尚无模型观测');return}const img=node('img');img.src=image.file;img.alt=`${view} ${image.image_ref}`;img.onclick=()=>{const z=$('zoom');z.querySelector('img').src=image.file;z.querySelector('p').textContent=`${image.image_ref} · ${image.sha256?'SHA '+image.sha256:'历史画面未验证模型接收'}`;z.showModal()};root.append(img);text(side+'-meta',`${image.image_ref} · rev ${obs.revision} · env.step ${image.env_steps??'—'}`);const target=s.arguments.target;if(side==='before'&&target&&typeof target==='object'&&target.image_ref===image.image_ref){const p=node('span',undefined,'point');p.style.left=target.point[0]*100+'%';p.style.top=target.point[1]*100+'%';p.title='模型传入的归一化像素目标；仅回放叠加';root.append(p)}}
function render(){paintTimeline();const s=D.steps[index];if(!s){text('step-title','没有可回放的工具调用');text('outcome',D.failure?JSON.stringify(D.failure):'启动阶段结束，未录到 agent 观测。');['prev','next','play','seek'].forEach(id=>$(id).disabled=true);text('position','0 / 0');frame('before',null,{arguments:{}});frame('after',null,{arguments:{}});return}text('position',`${index+1} / ${D.steps.length}`);$('seek').value=index+1;text('event',`${s.event_id} → ${s.result_event_id??'无返回'} · ${s.at}`);text('step-title',title(s));text('step-status',s.status==='passed'?'工具完成':s.status==='failed'?'调用被拒绝 / 失败':'缺少返回');$('step-status').className='badge '+s.status;frame('before',s.before,s);frame('after',s.after,s);text('frame-note',D.rgb_only?(s.new_observation?'本步返回RGB。十字仅表示模型本次传入的选点，原始输入图没有标注。':'本步没有返回新RGB；右侧沿用此前已返回的最近观测。'):'历史oracle协议：这些是仿真器归档画面，当时没有作为图像输入提供给模型。');text('action',s.tool==='act'?`${s.arguments.primitive||s.arguments.skill} · ${JSON.stringify(s.arguments.target)}`:s.tool==='look'?`原地转向 ${s.arguments.yaw_degrees}°（正值向左）`:s.tool==='read_skill'?`${s.arguments.name}/${s.arguments.resource}`:labels[s.tool]||s.tool);text('outcome',!s.result?'没有工具返回记录。':!s.result.ok?`${s.result.error?.code}: ${s.result.error?.message}`:s.result.effect?'底层操作报告完成；需要后续图像核查。':s.result.closed?'正式结束已接受；任务评分见下方独立评估。':s.tool==='observe'?'已返回当前观测。':'请求已接受。');text('timing',`距首个调用 ${s.elapsed_seconds.toFixed(2)} 秒 · 工具耗时 ${s.tool_seconds?.toFixed(2)??'—'} 秒`);text('arguments',JSON.stringify(s.arguments,null,2));text('result',JSON.stringify(s.result,null,2));$('decisions').replaceChildren();for(const m of s.model_messages||[]){const n=node('div',undefined,'decision');n.append(node('small',`原始公开消息 ${m.id} · 事件顺序 ${m.source_event_index}`),node('pre',m.text));$('decisions').append(n)}if(!s.model_messages?.length)$('decisions').append(node('p','此调用前没有新增的 LLM 公开文本。工具调用本身见左侧原始参数；不补写思考过程。','muted'));$('plan').replaceChildren();for(const g of s.plan){const n=node('div',undefined,'goal');n.append(node('strong',`${g.status} · ${g.id}`),node('div',g.description),node('small',`依赖 ${(g.dependencies||[]).join(', ')||'无'} · 证据 ${g.evidence||'未引用'}`));$('plan').append(n)}if(!s.plan.length)$('plan').append(node('p','尚无已接受的计划。','muted'));$('memory').replaceChildren();for(const [key,m]of Object.entries(s.memory)){const n=node('div',undefined,'memory');n.append(node('strong',`${key} · rev ${m.revision}`),node('div',m.text));$('memory').append(n)}if(!Object.keys(s.memory).length)$('memory').append(node('p','尚无记忆条目。','muted'));$('skill-detail').hidden=!(s.tool==='read_skill'&&s.result?.text);text('skill-text',s.result?.text||'');$('skill-card').hidden=!['list_skills','read_skill'].includes(s.tool);text('current-skill',s.result?.text||JSON.stringify(s.result?.skills||[],null,2));const chosen=visible();$('prev').disabled=!chosen.some(x=>x.index<s.index);$('next').disabled=!chosen.some(x=>x.index>s.index)}
function select(i){index=Math.max(0,Math.min(D.steps.length-1,i));if(!fromVideo&&D.video?.status==='passed'){const sec=edition==='explained'?D.explained_video.segments.find(p=>p.step===index+1)?.start_seconds:D.steps[index]?.video_start_seconds;if(sec!=null)$('episode-video').currentTime=Math.min(sec,$('episode-video').duration||sec)}if(D.steps.length)history.replaceState(null,'',`#step=${index+1}`);render()}
function advance(delta){const list=visible().filter(s=>delta>0?s.index>index+1:s.index<index+1);const next=delta>0?list[0]:list.at(-1);if(next)select(next.index-1);else stop()}
function stop(){if(timer)clearInterval(timer);timer=null;text('play','▶ 播放');$('play').classList.remove('playing')}
function play(){if(timer){stop();return}if(!visible().some(s=>s.index>index+1)){const first=visible()[0];if(!first)return;select(first.index-1)}text('play','Ⅱ 暂停');$('play').classList.add('playing');timer=setInterval(()=>advance(1),Number($('speed').value))}
text('title',D.config.task?`${D.config.task} / ${D.config.instance}`:D.run_id);text('instruction',D.instruction||'未记录任务指令');stat('stats','仿真后端',D.config.backend||'未记录');stat('stats','协议',D.rgb_only?'RGB → 理想执行器':'历史 Oracle');stat('stats','机器人动作',D.execution.actions??D.steps.filter(s=>s.is_motor_action).length);stat('stats','工具调用',D.steps.length);stat('stats','策略',D.model||D.config.policy||'未记录');const verified=D.audit?.evidence_alignment==='passed';text('protocol',D.rgb_only?`RGB闭环回放 · ${verified?'已核对控制器与仿真轨迹，以及实际传入模型的图像字节。':'尚未关联通过审计的模型图像传输记录。'} 大脑看图、按需读取 Skill、选点与核查，低层动作理想化。`:'历史oracle基线 · 模型当时收到真实对象状态和图片路径，没有收到RGB像素。本回放的画面仅辅助研究者审阅，不计入RGB实验成绩。');if(!D.rgb_only)$('protocol').classList.add('legacy');if(D.config.backend==='mock')text('protocol','CPU mock fixture：仅验证工具与记录软件，不是真实OmniGibson任务实验。');const e=D.evaluation_offline_only;stat('evaluation-stats','独立任务成功',e.task_success===true?'通过':e.task_success===false?'未完成':'未评测');stat('evaluation-stats','运行状态',D.status);stat('evaluation-stats','模型结束声明',e.agent_outcome||'没有正式结束');stat('evaluation-stats','BDDL Q',e.evaluation?.goal_satisfaction_fraction);text('evaluation',JSON.stringify({evaluation:e,source:D.source,execution:D.execution,backend:D.backend,failure:D.failure},null,2));text('audit-summary',D.audit?`证据对齐：${D.audit.evidence_alignment} · 实际ImageContent ${D.audit.rgb_evidence?.image_content_count??0} 个 · 独立图像 ${D.audit.rgb_evidence?.unique_model_image_count??0} 张 · 源码 ${D.source.commit}`:'无关联模型审计；仅展示本次仿真/脚本原始轨迹。');$('audit-link').hidden=!D.audit;text('limitations',D.limitations.join(' '));$('seek').max=Math.max(1,D.steps.length);$('seek').oninput=()=>{stop();select(Number($('seek').value)-1)};$('prev').onclick=()=>{stop();advance(-1)};$('next').onclick=()=>{stop();advance(1)};$('play').onclick=play;$('speed').onchange=()=>{if(timer){stop();play()}};$('filter').onchange=()=>{stop();const first=visible()[0];if(first&&!visible().some(s=>s.index===index+1))select(first.index-1);else render()};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()});$('close-zoom').onclick=()=>$('zoom').close();document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||$('zoom').open)return;if(e.key==='ArrowRight'){e.preventDefault();stop();advance(1)}if(e.key==='ArrowLeft'){e.preventDefault();stop();advance(-1)}if(e.code==='Space'){e.preventDefault();play()}});window.addEventListener('hashchange',()=>{const h=location.hash.match(/^#step=(\d+)$/);if(h){stop();select(Number(h[1])-1)}});
if(['minimal','skills'].includes(D.config.agent_profile)){$('workflow-panels').hidden=true;}

if(D.video?.status==='passed'){
 const v=$('episode-video');$('video-panel').hidden=false;
 const phaseNames={initial:'初始场景',decision:'LLM 公开原文 / 工具调用',execution:'执行工具',result:'工具返回与核查',evaluation:'独立评估（未提供给模型）'};
 function setEdition(){
  const record=edition==='explained'?D.explained_video:D.video;
  v.src=record.file;v.poster=record.poster;v.defaultPlaybackRate=1;v.playbackRate=Number($('video-speed').value);
  $('video-download').href=record.file;
  text('video-summary',edition==='explained'?`原始消息同步版 ${record.duration_seconds.toFixed(1)} 秒 · 原始 ${D.video.frame_count} 帧全部按顺序保留 · 额外阅读停顿已标注 · 1920×1080 / ${record.fps} FPS`:`原始录像 ${record.duration_seconds.toFixed(1)} 秒 · ${record.frame_count} 帧 · 连续覆盖 ${record.recorded_env_steps}/${record.final_env_step} 个控制步`);
 }
 $('video-edition').value=edition;
 if(!D.explained_video||D.explained_video.status!=='passed')$('video-edition').querySelector('[value="explained"]').disabled=true;
 $('video-edition').onchange=()=>{edition=$('video-edition').value;setEdition();v.addEventListener('loadedmetadata',()=>select(index),{once:true})};
 $('video-speed').onchange=()=>v.playbackRate=Number($('video-speed').value);
 v.addEventListener('timeupdate',()=>{
  let step;
  if(edition==='explained'){
   const segment=D.explained_video.segments.find(p=>p.start_seconds<=v.currentTime&&v.currentTime<p.end_seconds);
   step=segment?.step?D.steps[segment.step-1]:null;
   text('live-phase',`${step?'步骤 '+step.index+' / '+D.steps.length+' · ':''}${phaseNames[segment?.phase]||'播放结束'}${segment?.repeated_frame_hold?' · 阅读停顿（真实帧保持）':''}`);
  }else{
   step=D.steps.filter(s=>s.video_start_seconds!=null&&s.video_start_seconds<=v.currentTime).at(-1);
   text('live-phase',`原始仿真时间 ${v.currentTime.toFixed(1)} 秒 · ${step?'步骤 '+step.index+' · '+title(step):'初始画面'}`);
  }
  if($('video-sync').checked&&step&&step.index!==index+1){fromVideo=true;select(step.index-1);fromVideo=false}
 });
 setEdition();
}
$('public-trace-link').hidden=!D.has_public_trace;text('final-model-message',(D.model_final_messages||[]).map(m=>m.text).join('\n\n')||'没有单独的结束后公开文本。');
const hash=location.hash.match(/^#step=(\d+)$/);index=hash?Math.max(0,Math.min(D.steps.length-1,Number(hash[1])-1)):0;select(index);
})();
